from fastapi import APIRouter, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from io import BytesIO
from datetime import datetime

router = APIRouter()

class PDFRequest(BaseModel):
    title: str
    itinerary: str

@router.post("/generate")
def generate_pdf(req: PDFRequest):
    try:
        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer, pagesize=letter,
            rightMargin=0.75*inch, leftMargin=0.75*inch,
            topMargin=0.75*inch, bottomMargin=0.75*inch
        )
        story = []
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'Title', parent=styles['Heading1'], fontSize=28,
            textColor=colors.HexColor('#4F46E5'), spaceAfter=6,
            alignment=1, fontName='Helvetica-Bold'
        )
        subtitle_style = ParagraphStyle(
            'Subtitle', parent=styles['Normal'], fontSize=11,
            textColor=colors.HexColor('#6B7280'), spaceAfter=24,
            alignment=1, fontName='Helvetica'
        )
        day_heading_style = ParagraphStyle(
            'DayHeading', parent=styles['Heading2'], fontSize=16,
            textColor=colors.HexColor('#1F2937'), spaceAfter=10, spaceBefore=16,
            fontName='Helvetica-Bold',
        )
        activity_style = ParagraphStyle(
            'Activity', parent=styles['Normal'], fontSize=11,
            textColor=colors.HexColor('#374151'), spaceAfter=8,
            leading=14, leftIndent=20, fontName='Helvetica'
        )
        time_style = ParagraphStyle(
            'Time', parent=styles['Normal'], fontSize=10,
            textColor=colors.HexColor('#6366F1'), spaceAfter=4,
            fontName='Helvetica-Bold'
        )
        story.append(Paragraph(req.title, title_style))
        story.append(Paragraph(f"Generated on {datetime.now().strftime('%B %d, %Y')}", subtitle_style))
        story.append(Spacer(1, 0.2 * inch))
        lines = req.itinerary.split('\n')
        current_day = None
        for line in lines:
            if not line.strip():
                continue
            if line.startswith('## Day '):
                if current_day is not None:
                    story.append(Spacer(1, 0.15 * inch))
                    story.append(PageBreak())
                clean_line = line.replace('#', '').strip()
                story.append(Paragraph(clean_line, day_heading_style))
                current_day = clean_line
                continue
            if line.startswith('## '):
                clean_line = line.replace('#', '').strip()
                story.append(Spacer(1, 0.1 * inch))
                story.append(Paragraph(clean_line, styles['Heading3']))
                continue
            if any(char.isdigit() for char in line[:5]) and ':' in line[:5]:
                time_text = line.split(' ', 1)[0] + ' ' + (line.split(' ', 2)[1] if len(line.split(' ', 2)) > 1 else '')
                activity = ' '.join(line.split()[2:]) if len(line.split()) > 2 else line
                story.append(Paragraph(f"<b>{time_text}</b>", time_style))
                story.append(Paragraph(activity, activity_style))
                continue
            if line.strip().startswith('-') or line.strip().startswith('*'):
                clean_line = line.replace('-', '').replace('*', '').strip()
                story.append(Paragraph(f"• {clean_line}", activity_style))
                continue
            clean_line = line.strip()
            if clean_line:
                story.append(Paragraph(clean_line, styles['BodyText']))
        story.append(Spacer(1, 0.3 * inch))
        footer_style = ParagraphStyle(
            'Footer', parent=styles['Normal'], fontSize=9,
            textColor=colors.HexColor('#9CA3AF'), alignment=1
        )
        story.append(Paragraph("Safe travels! 🌍 Generated by AI Trip Planner", footer_style))
        doc.build(story)
        buffer.seek(0)
        return Response(
            content=buffer.getvalue(),
            media_type="application/pdf",
            headers={"Content-Disposition": "attachment; filename=trip-itinerary.pdf"}
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"PDF generation failed: {str(e)}")
