// frontend/src/components/ItinerarySection.jsx
import React, { useMemo, useState } from "react";
import RefineChat from "./RefineChat";

const defaultEmailForm = {
  to: "",
  subject: "Your personalized travel itinerary",
  message: "Here’s your personalized travel itinerary generated by AI Travel Planner.",
};

export default function ItinerarySection({
  itinerary,
  itineraryText,
  onDownloadPdf,
  onShareEmail,
  emailSending,
  refineMessages,
  onRefine,
  refineLoading,
  onSaveNote = () => { },
  savingNotes = {},
}) {
  const [shareLink, setShareLink] = useState("");
  const [emailModal, setEmailModal] = useState(false);
  const [emailForm, setEmailForm] = useState(defaultEmailForm);
  const [activeNoteDay, setActiveNoteDay] = useState(null);
  const [noteDraft, setNoteDraft] = useState("");
  const [expandedDays, setExpandedDays] = useState({});

  // Helper to parse raw text into structured days if structured data is missing
  const parseItineraryText = (text) => {
    if (!text) return [];
    const days = [];
    const lines = text.split('\n');
    let currentDay = null;
    let currentPeriod = null;

    // Regex to match "Day 1", "Day 1:", "Day 1 -", etc.
    const dayRegex = /^Day\s+(\d+)(?::|-)?\s*(.*)/i;

    lines.forEach(line => {
      const trimmed = line.trim();
      if (!trimmed) return;

      const dayMatch = trimmed.match(dayRegex);
      if (dayMatch) {
        if (currentDay) days.push(currentDay);
        currentDay = {
          day: dayMatch[1],
          headline: dayMatch[2] || `Day ${dayMatch[1]}`,
          segments: [],
          highlights: ""
        };
        currentPeriod = null;
      } else if (currentDay) {
        const lower = trimmed.toLowerCase();

        if (lower.includes("morning:")) {
          currentPeriod = "Morning";
          const content = trimmed.replace(/morning:/i, "").trim();
          if (content) currentDay.segments.push({ period: "Morning", activity: content });
        } else if (lower.includes("afternoon:")) {
          currentPeriod = "Afternoon";
          const content = trimmed.replace(/afternoon:/i, "").trim();
          if (content) currentDay.segments.push({ period: "Afternoon", activity: content });
        } else if (lower.includes("evening:")) {
          currentPeriod = "Evening";
          const content = trimmed.replace(/evening:/i, "").trim();
          if (content) currentDay.segments.push({ period: "Evening", activity: content });
        } else if (lower.includes("important notes:") || lower.includes("highlights:")) {
          currentDay.highlights = trimmed.replace(/(important notes:|highlights:)/i, "").trim();
          currentPeriod = null; // Reset period so subsequent lines don't get added to last period
        } else {
          // Append to current period or highlights
          if (currentPeriod) {
            const segs = currentDay.segments.filter(s => s.period === currentPeriod);
            if (segs.length > 0) {
              // If it looks like a new list item (bullet), add newline, else space
              const separator = (trimmed.startsWith("-") || trimmed.startsWith("•")) ? "\n" : " ";
              segs[segs.length - 1].activity += separator + trimmed;
            } else {
              // Period started but no content yet (e.g. "Morning:" was on prev line)
              currentDay.segments.push({ period: currentPeriod, activity: trimmed });
            }
          } else if (currentDay.highlights) {
            currentDay.highlights += "\n" + trimmed;
          } else if (!currentDay.headline && !currentPeriod) {
            // Maybe part of the headline if it was multiline?
            // Or just intro text for the day
          }
        }
      }
    });
    if (currentDay) days.push(currentDay);
    return days;
  };

  const days = useMemo(() => {
    if (itinerary?.days && itinerary.days.length > 0) return itinerary.days;
    return parseItineraryText(itineraryText);
  }, [itinerary, itineraryText]);

  const summaryCards = useMemo(() => {
    // Use the derived 'days' for length calculation
    const dest = itinerary?.destination || (itineraryText ? "Your Trip" : "—");
    return [
      { label: "Destination", value: dest, icon: "📍" },
      { label: "Duration", value: `${days.length || 0} days`, icon: "🗓️" },
      { label: "Theme", value: itinerary?.summary || "Balanced", icon: "✨" },
    ];
  }, [itinerary, days.length, itineraryText]);

  const hasContent = Boolean(itinerary || itineraryText);
  if (!hasContent) return null;

  const toggleDayDetails = (dayIndex) => {
    setExpandedDays(prev => ({ ...prev, [dayIndex]: !prev[dayIndex] }));
  };

  const categorizeSegments = (segments) => {
    const buckets = { Morning: [], Afternoon: [], Evening: [] };
    segments?.forEach(seg => {
      const p = (seg.period || "").toLowerCase();
      if (p.includes("morning") || p.includes("breakfast") || p.includes("am")) buckets.Morning.push(seg);
      else if (p.includes("afternoon") || p.includes("lunch") || p.includes("midday")) buckets.Afternoon.push(seg);
      else buckets.Evening.push(seg);
    });
    return buckets;
  };

  const handleShareLink = async () => {
    try {
      const payload = { itineraryText, itinerary, generatedAt: Date.now() };
      const shareId = btoa(JSON.stringify(payload)).slice(0, 24);
      const baseUrl = window.location.origin + window.location.pathname.replace(/\/[^/]*$/, "");
      const link = `${baseUrl}/share/${shareId}`;
      await navigator.clipboard.writeText(link);
      setShareLink(link);
      alert("Shareable link copied to clipboard!");
    } catch (error) {
      console.error(error);
      alert("Unable to create share link.");
    }
  };

  const handleEmailSubmit = async (e) => {
    e.preventDefault();
    if (!emailForm.to) return;
    await onShareEmail({ ...emailForm });
    setEmailModal(false);
    setEmailForm(defaultEmailForm);
  };

  const openNoteEditor = (day) => {
    setActiveNoteDay(day.day);
    setNoteDraft(day.personal_note || "");
  };

  const handleNoteSubmit = (day) => {
    onSaveNote(day.day, noteDraft);
    setActiveNoteDay(null);
  };

  const renderSegment = (seg, idx) => (
    <div key={idx} className="sub-card-item">
      <div className="sub-card-header">
        <span className="activity-name">{seg.activity}</span>
      </div>
      <div className="sub-card-meta">
        {seg.food && <span className="tag-food">🍽 {seg.food}</span>}
        {seg.tips && seg.tips[0] && <span className="tag-tip">💡 {seg.tips[0]}</span>}
      </div>
    </div>
  );

  const renderDayCard = (day, idx) => {
    const buckets = categorizeSegments(day.segments);
    const isExpanded = expandedDays[idx];

    return (
      <article key={day.day || idx} className="day-card-new">
        <header className="day-header-new">
          <div className="day-title-group">
            <span className="day-number">🗓️ Day {day.day}</span>
            <h4 className="day-headline">{day.headline || day.date}</h4>
          </div>
          <span className="day-date-muted">{day.date}</span>
        </header>

        {day.highlights && (
          <div className="day-highlights-wrapper">
            <h5 className="highlights-label">💡 Important Notes</h5>
            <p className="day-highlights-text">{day.highlights}</p>
          </div>
        )}

        <div className="day-periods-grid">
          {["Morning", "Afternoon", "Evening"].map((period) => (
            <div key={period} className="period-column">
              <h5 className="period-title">
                {period === "Morning" ? "🌅" : period === "Afternoon" ? "☀️" : "🌙"} {period}
              </h5>
              <div className="period-content">
                {buckets[period].length > 0 ? (
                  <>
                    {renderSegment(buckets[period][0], 0)}
                    {buckets[period].length > 1 && (
                      <>
                        {isExpanded && buckets[period].slice(1).map((s, i) => renderSegment(s, i + 1))}
                        {!isExpanded && (
                          <button className="btn-more-activities" onClick={() => toggleDayDetails(idx)}>
                            + {buckets[period].length - 1} more
                          </button>
                        )}
                      </>
                    )}
                  </>
                ) : (
                  <span className="empty-period">Free time</span>
                )}
              </div>
            </div>
          ))}
        </div>

        <div className="day-summary-strip">
          <div className="strip-item">
            <span className="icon">🧭</span>
            <span>{day.travel_time || "—"}</span>
          </div>
          <div className="strip-item">
            <span className="icon">💰</span>
            <span>{day.budget_tip || "Est. $50-100"}</span>
          </div>
          <div className="strip-item note-trigger-wrapper">
            {activeNoteDay === day.day ? (
              <form
                className="inline-note-form"
                onSubmit={(e) => { e.preventDefault(); handleNoteSubmit(day); }}
              >
                <input
                  autoFocus
                  value={noteDraft}
                  onChange={(e) => setNoteDraft(e.target.value)}
                  placeholder="Add note..."
                  onBlur={() => handleNoteSubmit(day)} // Auto-save on blur
                />
              </form>
            ) : (
              <button className="btn-quick-note" onClick={() => openNoteEditor(day)}>
                {day.personal_note ? `📝 ${day.personal_note}` : "+ Add quick note"}
              </button>
            )}
          </div>
        </div>
      </article>
    );
  };

  return (
    <section className="itinerary-layout">
      {/* Main Content Column */}
      <div className="itinerary-main">
        {/* Header Actions */}
        <div className="itinerary-header-row">
          <div className="header-actions">
            <button className="btn-action-subtle" onClick={handleShareLink}>🔗 Share</button>
            <button className="btn-action-subtle" onClick={onDownloadPdf}>📥 PDF</button>
          </div>
        </div>

        {shareLink && <div className="share-toast">Link copied: {shareLink}</div>}

        <div className="days-container">
          {days.length > 0 ? days.map(renderDayCard) : (
            <div className="text-only-fallback">
              {itineraryText?.split("\n").map((line, i) => <p key={i}>{line}</p>)}
            </div>
          )}
        </div>

        <div className="refine-section-wrapper">
          <h3>Refine your trip</h3>
          <RefineChat messages={refineMessages} onSend={onRefine} loading={refineLoading} />
        </div>
      </div>

      {/* Sticky Sidebar Column */}
      <aside className="itinerary-sidebar">
        <div className="sidebar-widget summary-widget">
          <h4>Trip Summary</h4>
          <div className="widget-row">
            <span>Total Days</span>
            <strong>{days.length}</strong>
          </div>
          <div className="widget-row">
            <span>Est. Budget</span>
            <strong>$1,200 - $1,500</strong>
          </div>
          <hr />
          <button className="btn-primary-full" onClick={() => document.querySelector('.refine-section-wrapper').scrollIntoView({ behavior: 'smooth' })}>
            ✨ Refine Itinerary
          </button>
          <button className="btn-secondary-full" onClick={() => setEmailModal(true)}>
            📤 Share via Email
          </button>
        </div>
      </aside>

      {emailModal && (
        <div className="email-share-overlay" role="dialog">
          <div className="email-share-card">
            <header>
              <h4>Share via Email</h4>
              <button onClick={() => setEmailModal(false)}>✕</button>
            </header>
            <form onSubmit={handleEmailSubmit}>
              <label>To <input type="email" value={emailForm.to} onChange={e => setEmailForm({ ...emailForm, to: e.target.value })} required /></label>
              <label>Subject <input type="text" value={emailForm.subject} onChange={e => setEmailForm({ ...emailForm, subject: e.target.value })} required /></label>
              <label>Message <textarea value={emailForm.message} onChange={e => setEmailForm({ ...emailForm, message: e.target.value })} rows={4} /></label>
              <div className="email-actions">
                <button type="button" onClick={() => setEmailModal(false)}>Cancel</button>
                <button type="submit" disabled={emailSending}>{emailSending ? "Sending..." : "Send"}</button>
              </div>
            </form>
          </div>
        </div>
      )}
    </section>
  );
}
