// frontend/src/components/ItinerarySection.jsx
import React, { useMemo, useState } from "react";
import RefineChat from "./RefineChat";

const defaultEmailForm = {
  to: "",
  subject: "Your personalized travel itinerary",
  message: "Here’s your personalized travel itinerary generated by AI Travel Planner.",
};

export default function ItinerarySection({
  itinerary,
  itineraryText,
  onDownloadPdf,
  onShareEmail,
  emailSending,
  refineMessages,
  onRefine,
  refineLoading,
  onSaveNote = () => {},
  savingNotes = {},
}) {
  const [shareLink, setShareLink] = useState("");
  const [emailModal, setEmailModal] = useState(false);
  const [emailForm, setEmailForm] = useState(defaultEmailForm);
  const [activeNoteDay, setActiveNoteDay] = useState(null);
  const [noteDraft, setNoteDraft] = useState("");

  const days = itinerary?.days || [];
  const summaryCards = useMemo(() => {
    if (!itinerary) return [];
    return [
      { label: "Destination", value: itinerary.destination || "—" },
      { label: "Duration", value: `${days.length || 0} days` },
      { label: "Theme", value: itinerary.summary || "Balanced pacing" },
    ];
  }, [itinerary, days.length]);
  const hasContent = Boolean(itinerary || itineraryText);
  if (!hasContent) return null;

  const handleShareLink = async () => {
    try {
      const payload = {
        itineraryText,
        itinerary,
        generatedAt: Date.now(),
      };
      const shareId = btoa(JSON.stringify(payload)).slice(0, 24);
      const baseUrl = window.location.origin + window.location.pathname.replace(/\/[^/]*$/, "");
      const link = `${baseUrl}/share/${shareId}`;
      await navigator.clipboard.writeText(link);
      setShareLink(link);
      alert("Shareable link copied to clipboard!");
    } catch (error) {
      console.error(error);
      alert("Unable to create share link.");
    }
  };

  const handleEmailSubmit = async (e) => {
    e.preventDefault();
    if (!emailForm.to) return;
    await onShareEmail({
      to: emailForm.to,
      subject: emailForm.subject,
      message: emailForm.message,
    });
    setEmailModal(false);
    setEmailForm(defaultEmailForm);
  };

  const openNoteEditor = (day) => {
    setActiveNoteDay(day.day);
    setNoteDraft(day.personal_note || "");
  };

  const handleNoteSubmit = (day) => {
    onSaveNote(day.day, noteDraft);
    setActiveNoteDay(null);
  };

  const renderDayCard = (day, idx) => (
    <article key={day.day || idx} className="itinerary-day-card">
      <header className="itinerary-day-head">
        <div>
          <p className="eyebrow">Day {day.day}</p>
          <h4>{day.headline || day.date}</h4>
        </div>
        <span className="muted">{day.date}</span>
      </header>
      {day.highlights && <p className="day-highlights">{day.highlights}</p>}
      <div className="segments-grid">
        {day.segments?.map((seg, i) => (
          <div key={i} className="segment-card">
            <div className="segment-period">{seg.period}</div>
            <p className="segment-activity">{seg.activity}</p>
            {seg.food && <p className="segment-meta">🍽 {seg.food}</p>}
            {seg.tips && seg.tips.length > 0 && <p className="segment-meta">💡 {seg.tips[0]}</p>}
          </div>
        ))}
      </div>
      <div className="day-meta">
        {day.travel_time && <span>🧭 {day.travel_time}</span>}
        {day.weather_note && <span>🌤 {day.weather_note}</span>}
        {day.safety_tip && <span>🛡 {day.safety_tip}</span>}
        {day.budget_tip && <span>💰 {day.budget_tip}</span>}
      </div>
      {day.notes && day.notes.length > 0 && (
        <ul className="day-notes">
          {day.notes.map((note, noteIdx) => (
            <li key={noteIdx}>{note}</li>
          ))}
        </ul>
      )}
      <div className="day-note-footer">
        {day.personal_note ? <span className="muted">📝 {day.personal_note}</span> : <span className="muted">Add a quick note</span>}
        <button
          type="button"
          className="day-note-trigger"
          onClick={() => openNoteEditor(day)}
          aria-label={`Add note for day ${day.day}`}
        >
          📝
        </button>
      </div>
      {activeNoteDay === day.day && (
        <form
          className="day-note-editor"
          onSubmit={(e) => {
            e.preventDefault();
            handleNoteSubmit(day);
          }}
        >
          <textarea
            value={noteDraft}
            maxLength={180}
            onChange={(e) => setNoteDraft(e.target.value)}
            placeholder="Add a short personal reminder..."
          />
          <div className="note-actions">
            <button type="button" onClick={() => setActiveNoteDay(null)}>
              Cancel
            </button>
            <button type="submit" disabled={Boolean(savingNotes[day.day])}>
              {savingNotes[day.day] ? "Saving..." : "Save"}
            </button>
          </div>
        </form>
      )}
    </article>
  );

  return (
    <section className="itinerary-expanded">
      <div className="card itinerary-card">
        <div className="card-header itinerary-card-head">
          <div>
            <p className="eyebrow">Itinerary</p>
            <h3>Orchestrated day-by-day plan</h3>
          </div>
          <div className="itinerary-actions">
            <button className="btn-share" onClick={handleShareLink}>
              🔗 Share link
            </button>
            <button className="btn-share" onClick={() => setEmailModal(true)} disabled={emailSending}>
              {emailSending ? "Sending..." : "📤 Share via email"}
            </button>
            <button className="btn-download" onClick={onDownloadPdf}>
              📥 Download PDF
            </button>
          </div>
        </div>
        {shareLink && (
          <p className="share-link-hint muted">
            Link copied • {shareLink}
          </p>
        )}

        {summaryCards.length > 0 && (
          <div className="itinerary-summary-grid">
            {summaryCards.map((card) => (
              <div key={card.label} className="summary-card">
                <span>{card.label}</span>
                <strong>{card.value}</strong>
              </div>
            ))}
          </div>
        )}

        {days.length > 0 ? (
          <div className="itinerary-days-grid">{days.map(renderDayCard)}</div>
        ) : (
          <div className="itinerary-body">
            {itineraryText?.split("\n").map((line, idx) =>
              line.trim() ? (
                <p key={idx} className="itinerary-line">
                  {line}
                </p>
              ) : (
                <br key={idx} />
              )
            )}
          </div>
        )}
      </div>

      <RefineChat messages={refineMessages} onSend={onRefine} loading={refineLoading} />

      {emailModal && (
        <div className="email-share-overlay" role="dialog" aria-modal="true">
          <div className="email-share-card">
            <header>
              <h4>Share via Email</h4>
              <button onClick={() => setEmailModal(false)}>✕</button>
            </header>
            <form onSubmit={handleEmailSubmit}>
              <label>
                Recipient email
                <input
                  type="email"
                  value={emailForm.to}
                  onChange={(e) => setEmailForm((prev) => ({ ...prev, to: e.target.value }))}
                  placeholder="traveler@example.com"
                  required
                />
              </label>
              <label>
                Subject
                <input
                  type="text"
                  value={emailForm.subject}
                  onChange={(e) => setEmailForm((prev) => ({ ...prev, subject: e.target.value }))}
                  required
                />
              </label>
              <label>
                Message
                <textarea
                  value={emailForm.message}
                  onChange={(e) => setEmailForm((prev) => ({ ...prev, message: e.target.value }))}
                  rows={4}
                />
              </label>
              <div className="email-actions">
                <button type="button" onClick={() => setEmailModal(false)}>
                  Cancel
                </button>
                <button type="submit" disabled={emailSending}>
                  {emailSending ? "Sending..." : "Send itinerary"}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </section>
  );
}
